# MinGW-w64 交叉编译 toolchain（Windows x86_64，winlibs GCC 16.2 UCRT）
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_ROOT "/opt/mingw/mingw64" CACHE PATH "MinGW-w64 根目录")
set(QT_MINGW_ROOT "/opt/qtwin/6.8.3/mingw_64" CACHE PATH "Qt Windows MinGW 根目录")

set(CMAKE_C_COMPILER   "${MINGW_ROOT}/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "${MINGW_ROOT}/bin/g++.exe")
set(CMAKE_RC_COMPILER  "${MINGW_ROOT}/bin/windres.exe")

set(CMAKE_FIND_ROOT_PATH "${QT_MINGW_ROOT}" "${MINGW_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_PREFIX_PATH "${QT_MINGW_ROOT}")
